[project]
name = "finst-video-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Keith Murray", email = "murraykeith64@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.1",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
finst-video-model = "finst_video_model:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
