"""
Follow-up to run_gemma_frame_budget_sweep.py (see reference_gemma_fixed_frame_
budget memory): that sweep measured google/gemma-4-31b-it's frame-sampling
cap at ~33 real frames, but never pinned `provider` -- OpenRouter's raw
response includes a top-level `provider` field naming which endpoint served
each call, and an unpinned ad hoc check on that sweep's own n=1 video came
back served by `ModelRun`, not `DeepInfra` (this project's usual pricing/
routing assumption) -- see reference_openrouter_provider_routing_gotchas
memory, item 4. This script re-runs the same frame-count sweep once per
provider, with `provider={"only": [p], "allow_fallbacks": False}` pinned via
vlm_client.ask_about_video, to check whether the ~33-frame cap (and the
~73-tokens/frame rate) is a property of the model itself or varies by
serving endpoint.

Reuses the exact same videos generated by run_gemma_frame_budget_sweep.py
(data/debug_circular/frame_budget_sweep/n{N:02d}_rep0.mp4) rather than
regenerating them -- content only depends on n_frames/rep, not provider.

Providers swept: only those confirmed (2026-09-08 smoke test) to actually
serve video input for this model -- deepinfra, coreweave, chutes, crusoe,
parasail, together, modelrun. Excluded: friendli (422 Unprocessable Entity),
sambanova (502 Bad Gateway), cerebras (404 Not Found) -- all reproduced
twice, so treated as not currently serving video for this model rather than
a transient flake.

1 rep per (provider, n_frames) -- determinism given frame count was already
established by the original sweep (0 errors, near-exact rep agreement), so
this only checks for a provider-dependent shift in the cap/rate, not
per-provider noise.

Usage:
    uv run python scripts/debug_circular/run_gemma_frame_budget_provider_sweep.py
    uv run python scripts/debug_circular/run_gemma_frame_budget_provider_sweep.py --max-frames 45
"""

import argparse
import csv
import os

import requests

from finst_video_model.vlm_client import ask_about_video

SOURCE_VIDEO_DIR = "data/debug_circular/frame_budget_sweep"
RUN_NAME = "frame_budget_provider_sweep"
MODEL = "google/gemma-4-31b-it"
QUESTION = "Describe what you see in this video in one sentence."

PROVIDERS = ["deepinfra", "coreweave", "chutes", "crusoe", "parasail", "together", "modelrun"]

RESULT_FIELDS = [
    "provider_pinned", "n_frames", "rep", "model", "served_by_provider",
    "response", "prompt_tokens", "completion_tokens", "cost", "error",
]


def run_one(provider: str, n_frames: int, rep: int) -> dict:
    video_path = os.path.join(SOURCE_VIDEO_DIR, f"n{n_frames:02d}_rep{rep}.mp4")
    row = {
        "provider_pinned": provider, "n_frames": n_frames, "rep": rep, "model": MODEL,
        "served_by_provider": "", "response": "", "prompt_tokens": "",
        "completion_tokens": "", "cost": "", "error": "",
    }
    try:
        response_text, usage = ask_about_video(
            video_path, QUESTION, MODEL,
            provider={"only": [provider], "allow_fallbacks": False},
            reasoning={"enabled": False}, return_usage=True,
        )
        row.update({
            "served_by_provider": (usage or {}).get("served_by_provider"),
            "response": response_text,
            "prompt_tokens": (usage or {}).get("prompt_tokens"),
            "completion_tokens": (usage or {}).get("completion_tokens"),
            "cost": (usage or {}).get("cost"),
        })
    except (requests.RequestException, KeyError, RuntimeError) as e:
        row["error"] = str(e)
    return row


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-frames", type=int, default=45)
    parser.add_argument("--providers", type=str, nargs="+", default=PROVIDERS)
    args = parser.parse_args()

    results_dir = os.path.join("results", "debug_circular", RUN_NAME)
    os.makedirs(results_dir, exist_ok=True)

    results_csv = os.path.join(results_dir, "results.csv")
    already_ran = set()
    file_exists = os.path.isfile(results_csv)
    if file_exists:
        with open(results_csv) as f:
            for r in csv.DictReader(f):
                already_ran.add((r["provider_pinned"], int(r["n_frames"]), int(r["rep"])))

    grid = [
        (provider, n_frames, 0)
        for provider in args.providers
        for n_frames in range(1, args.max_frames + 1)
        if (provider, n_frames, 0) not in already_ran
    ]
    total = len(args.providers) * args.max_frames
    done = len(already_ran)

    with open(results_csv, "a", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=RESULT_FIELDS)
        if not file_exists:
            writer.writeheader()
            csv_file.flush()

        for provider, n_frames, rep in grid:
            row = run_one(provider, n_frames, rep)
            done += 1
            print(
                f"[{done}/{total}] provider={provider} n_frames={n_frames} "
                f"prompt_tokens={row['prompt_tokens']} served_by={row['served_by_provider']} "
                f"error={row['error']}"
            )
            writer.writerow(row)
            csv_file.flush()

    print(f"\nresults.csv up to date at {results_csv}")


if __name__ == "__main__":
    main()
